version: '3.8'

services:
  php:
    container_name: hlapp
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        APP_ENV: local
    ports:
      - "127.0.0.1:${APP_PORT:-9005}:80"
    volumes:
      - ./backend:/app
    command: ["frankenphp", "run", "--config", "/etc/frankenphp/Caddyfile"]
    networks:
      - hotelinking
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - APP_ENV=${APP_ENV}
      - APP_URL=${APP_URL}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - HR_SSO_VERIFY_URL=${HR_SSO_VERIFY_URL}
      - MOCK_SSO=${MOCK_SSO}
      - APP_SECURE_URL=${APP_SECURE_URL}
      - API_URL=${API_URL}
      - HR_SSO_DOMAIN=${HR_SSO_DOMAIN}
    restart: unless-stopped

networks:
  hotelinking:
    name: hotelinking
    external: true
