version: '3.8'

services:
  php:
    container_name: hlapp
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        APP_ENV: local
    ports:
      - "9005:80"
      - "9006:443"
      - "9006:443/udp"
    volumes:
      - ./backend:/app
    command: ["frankenphp", "run", "--config", "/etc/frankenphp/Caddyfile"]
    networks:
      - hotelinking
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - APP_ENV=dev
      - APP_URL=http://localhost:9005/
      - DB_HOST=hlmysql8
      - DB_DATABASE=hotelinking_app_local
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - REDIS_HOST=redis
      - HR_SSO_VERIFY_URL=https://hr.mediusware.xyz/api/demo/validate/
      - MOCK_SSO=true
    restart: unless-stopped

networks:
  hotelinking:
    name: hotelinking
    external: true
