<?php //Miramos si esta definida la variable de control de index.php
if(!defined('INDEXCONTROLVAL')){echo 'No direct access allowed.';exit;} ?>

<?php if(isset($_SESSION['h_logueado'])){
	echo '<div id="wrapper">';
	include TEMPLATES . 'hotel-sidebar.php';
}?>
<div id="page-content-wrapper">
	<?php if(isset($_SESSION['h_logueado'])){ ?>
        <div class="top-bar">
            <img class="topbarLogo visible-xs" src="<?php echo DIR_IMG . 'topbar-logo-xs.png' ?>" width="77" height="70"
                 alt="top bar logo">
        </div>
	<?php } ?>
		<div class="utility-bar">
			<div class="col-lg-12">
				<h1 class="pull-left"><i class="fa fa-gavel"></i> Terms and conditions</h1>
				<div class="breadcrumbs pull-right">
					<ul>
						<?php include (TEMPLATES .'breadcrumbs.php'); ?>
					</ul>
				</div>
			</div>
		</div>
	<div class="clearfix"></div>
	<div class="row">
		<div class="container">
			<h2>Guest Terms and Conditions</h2>
			<h3>Your Registration Obligations</h3>
			<p>You are required to register with Hotelinking in order to access and use certain features of the Service. If you choose to register for the Service, you agree to provide and maintain true, accurate, current and complete information about yourself as prompted by the Service’s registration form. Registration data and certain other information about you are governed by our Privacy Policy. If you are under 13 years of age, you are not authorized to use the Service, with or without registering. In addition, if you are under 18 years old, you may use the Service, with or without registering, only with the approval of your parent or guardian.</p>
			<h3>Member Account, Password and Security</h3>
			<p>You are responsible for maintaining the confidentiality of your password and/or mobile device, as applicable, and account, if any, and are fully responsible for any and all activities that occur under your password and/or mobile device, as applicable, or account. You agree to (a) immediately notify Hotelinking of any unauthorized use of your password and/or mobile device, as applicable, or account or any other breach of security, and (b) ensure that you exit from your account at the end of each session when accessing the Service. Hotelinking will not be liable for any loss or damage arising from your failure to comply with this Section.</p>
			<h3>Modifications to Service</h3>
			<p>Hotelinking reserves the right to modify or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice. You agree that Hotelinking shall not be liable to you or to any third party for any modification, suspension or discontinuance of the Service.</p>
			<h3>Rewards</h3>
			<p>All Rewards made available in connection with the Service are promotional only. Such Rewards are made available directly by the relevant Hotel providing such Reward (“Rewards Provider”) (not Hotelinking itself) and are redeemable solely for the applicable goods or services of the relevant Rewards Provider. The Rewards Provider, not Hotelinking, is the provider of the Rewards and such goods and services and is solely responsible for redeeming any Rewards you obtain. Hotelinking will have no liability if a Rewards Provider refuses or fails to honor any Reward. In addition, the following terms and conditions also apply to all Rewards:</p>
			<ul>
				<li>Redemption frequency is determined by the Rewards Provider.</li>
				<li>Use of Rewards relating to alcoholic beverages is at the sole discretion of the Rewards Provider and is subject to compliance with applicable law.</li>
				<li>Rewards can be combined with any other rewards, offers, vouchers, third party certificates, coupons, or promotions, unless otherwise specified by the Rewards Provider.</li>
				<li>Rewards cannot be used for taxes, tips or prior balances, unless permitted by the Rewards Provider.</li>
				<li>Neither Hotelinking nor the Rewards Provider is responsible for malfunctioning, lost, or stolen cards.</li>
				<li>Reproduction or sale of any Reward is prohibited.</li>
				<li>Any attempted redemption not consistent with these Terms of Use or any other restrictions imposed by the Rewards Provider or Hotelinking (including any Reward-specific terms associated with a Reward) will render the Reward void.</li>
				<li>Rewards are void to the extent prohibited by law.</li>
				<li>Rewards may be applied only to the applicable products or services sold by the Rewards Provider that are the subject of such Rewards.</li>
				<li>Limit one (1) Reward per redemption. Only one Reward can be used per redemption unless otherwise specified by the Rewards Provider.</li>
			</ul>
			<h2>Hotel Terms and Conditions</h2>
			<h3>General</h3>
			<p>During the length of the Hotel Agreement, Hotelinking will provide the Hotelinking services and/or programs (collectively, "Hotelinking Programs") described in the Hotel Agreement separately executed by you, together with all exhibits attached thereto (the "Hotel Agreement"). In the event of any inconsistency among terms and conditions of the Hotel Agreement and these Terms and Conditions (collectively, sometimes referred to herein as the "Agreement"), the order of control shall be: (i) these Terms and Conditions, (ii) the Hotel Agreement, and (iii) any other exhibits, addenda or attachments to these Terms and Conditions including any links contained in the Hotel Agreement or these Terms and Conditions, which are incorporated by reference herein. Any capitalized terms that are not defined in these Terms and Conditions have the meanings ascribed to them in the Hotel Agreement. For purposes of clarity, these Terms and Conditions are incorporated by reference into the Hotel Agreement executed by you, and, together with the Hotel Agreement and all attachments thereto, govern your use of all Hotelinking Programs and services.</p>
			<h3>Intellectual Property Rights</h3>
			<ol>
				<li>Hotelinking is the sole and exclusive owner of all right, title and interest in and to any data provided to Hotelinking by your guests or any end user to Hotelinking in connection with the Hotelinking Programs, including without limitation all e-mail and/or other contact information ("Guest Data"). As such, you shall not, unless the applicable guest has separately taken all steps necessary to opt in to provide contact information to you, be provided with or otherwise have access to the Guest Data.</li>
				<li>Hotelinking owns all right, title and interest in and to the Hotelinking Programs including, without limitation, any intellectual property rights and any improvements, modifications, enhancements or refinements thereto. Except as set forth in the Agreement, all rights not expressly granted to you are reserved. You agree not to decipher, decompile, disassemble, reconstruct, translate, reverse engineer, or discover any of the Hotelinking Programs, intellectual property or ideas, algorithms, file formats, programming, or interoperability interfaces underlying or such intellectual property.</li>
				<li>Hotelinking hereby grants to you a limited, non-transferable, non-exclusive, revocable license to access and use Hotelinking hosted Hotel Web Portal for internal business purposes so long as your account with Hotelinking remains current and active. If Hotelinking provides you with a password to access the Portal, you are solely responsible for protecting the password and for any authorized or unauthorized use made of the password. The Portal, and all source code, copyrights and other intellectual property associated therewith, are and shall remain the sole and exclusive property of Hotelinking. You shall refrain from permitting any third party to use your password or otherwise access the Portal. Hotelinking shall have the right to terminate the license granted hereby immediately in the event that you have breached any terms or conditions set forth in the Agreement or your Hotelinking account is otherwise terminated for any reason.</li>
				<li>Hotelinking provides standard installation of its Hotelinking Programs, however, in the event of a complex installation (including those that may require third party or outside technical support to complete the installation), Hotelinking will provide up to one hour of such technical support. Technical support exceeding one hour will be billed at cost to the Hotel.</li>
			</ol>
			<h3>Restrictions</h3>
			<p>You: (i) will use the Hotelinking Programs solely for your internal business purposes; and (ii) will not, for yourself, any of your affiliates or any third party (a) sell, rent, lease, license or sublicense, assign, distribute, or transfer the Hotelinking Programs, (b) modify, change, alter, create derivative works of, decipher, decompile, disassemble, reconstruct, translate, reverse engineer, or discover any source code of the underlying ideas, algorithms, file formats, programming, or interoperability interfaces of the Hotelinking Programs, (c) copy any tangible versions of the Hotelinking Programs, or (d) remove from any of the Hotelinking Programs any language or designation indicating the confidential nature thereof or the proprietary rights of Hotelinking. In addition, you will not export, re-export or permit any third party to export or re-export, directly or indirectly, the Hotelinking Programs where such export or re-export is prohibited by applicable law without appropriate licenses and clearances. Hotelinking retains the right, in its sole discretion, to approve, modify or refuse any Hotelinking related communications or proposed communications or messages to your guests or any Hotelinking end users.</p>
			<h3>Fees; Pricing and Payment Terms; Taxes</h3>
			<ul>
				<li>Hotelinking’s current fees for the Hotelinking Programs and its services are set forth in the Hotel Agreement. Hotelinking reserves the right to amend the fees payable for the Hotelinking Programs at any time upon thirty (30) days’ prior notice to you; provided, however, that such amendment to the fees will not be applicable until the beginning of the next Subscription Period.</li>
				<li>When you provide your payment information to Hotelinking, you are providing Hotelinking with an authorization to process any and all payments as outlined in this Agreement. In certain instances, the payment processing may not occur immediately, and your payment may show as "pending" during this time period. In addition, Hotelinking may request an authorization for the amount of your anticipated transaction in advance and may estimate the final value of the transaction, which may be more than the amount of the actual transaction. Hotelinking will release any funds authorized in excess of the amount of the actual transaction at the time the transaction settles.</li>
				<li>You will be responsible for any sales, use, value-added or import taxes, customs duties or similar taxes assessed in accordance with applicable law with respect to the provision of the Hotelinking Programs.</li>
				<li>Notwithstanding anything herein to the contrary, Hotelinking, in its sole discretion, may suspend or terminate the Agreement and corresponding access and right to use all or any portion of the Hotelinking Programs, at any time, upon electronic or other notice to you, if you have not paid all amounts due on or before the payment due date, or for any other breaches of the Hotel Agreement, these Terms and Conditions, or any other exhibits, addenda or attachments to these Terms and Conditions including any links contained in the Hotel Agreement or these Terms and Conditions, which are incorporated by reference herein. You are responsible for amounts that remain outstanding as of the date of such termination including early cancellation fees. You agree to pay reasonable attorneys’ fees and court costs incurred by Hotelinking to collect any unpaid amounts owed by you.</li>
				<li>Hotelinking provides standard installation of its Hotelinking Programs, however, in the event of a complex installation (including those that may require third party or outside technical support to complete the installation), Hotelinking will provide up to one hour of such technical support. Technical support exceeding one hour will be billed at cost to the Hotel.</li>
			</ul>
			<h3>Termination</h3>
			<p>You agree that Hotelinking, in its sole discretion, may suspend or terminate your account (or any part thereof) or use of the Service for any reason, including, without limitation, for lack of use or if Hotelinking believes that you have violated or acted inconsistently with the letter or spirit of these Terms of Use. Any suspected fraudulent, abusive or illegal activity that may be grounds for termination of your use of Service and may be referred to appropriate law enforcement authorities. Hotelinking may also in its sole discretion and at any time discontinue providing the Service, or any part thereof, with or without notice. You agree that any termination of your access to the Service under any provision of this Terms of Use may be effected without prior notice, and acknowledge and agree that Hotelinking may immediately deactivate or delete your account and all of your related Rewards. Further, you agree that Hotelinking shall not be liable to you or any third-party for any termination of your access to the Service.</p>
			<h3>Representations and Warranties</h3>
			<ul>
				<li>Hotelinking warrants that Hotelinking has the authority to enter into this Agreement.</li>
				<li>You represent, warrant and covenant to Hotelinking that: (a) you have the authority to enter into this Agreement; (b) you will take proper care of the Hotelinking Kit and/or all equipment provided by Hotelinking to you and maintain all such equipment in good working order; and (c) you will only use the Hotelinking Programs for lawful purposes and will not violate any law of any country or the intellectual property rights of any third party.</li>
				<li>EXCEPT AS SPECIFICALLY PROVIDED IN THIS SECTION, EACH PARTY EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, INCLUDING WITHOUT LIMITATION THE IMPLIED WARRANTIES OF QUALITY, ACCURACY, HOTEL ABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN ADDITION, HOTELINKING DOES NOT MAKE ANY REPRESENTATIONS OR WARRANTIES AS TO THE RESULTS THAT YOU MAY ACHIEVE ON ACCOUNT USING ANY HOTELINKING PROGRAM OR SERVICE. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, YOU EXPRESSLY AGREE THAT THE USE OF HOTELINKING PROGRAMS OR SERVICES AND THE INTERNET IS AT YOUR SOLE RISK. HOTELINKING PROGRAMS AND SERVICES ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. YOU HEREBY ACKNOWLEDGE THAT YOU ARE SOLELY RESPONSIBLE FOR OBTAINING AND/OR PROVIDING INTERNET SERVICE TO ALL LOCATIONS IN WHICH THE HOTELINKING PROGRAMS ARE TO OPERATE.</li>
			</ul>
			<h3>Confidential Information</h3>
			<p>Any information that a receiving party knows or has reason to know (either because such information is marked or otherwise identified by the disclosing party orally or in writing as confidential or proprietary, has commercial value, or because it is not generally known in the relevant trade or industry) is "Confidential Information" of the disclosing party and will remain the sole property of the disclosing party. Such Confidential Information includes but is not limited to data, information (including personally identifiable information), ideas, materials, specifications, procedures, schedules, software, technical processes and formulas, source code, product designs, sales, cost and other unpublished financial information, product and business plans, advertising revenues, usage rates, advertising relationships, projections, marketing data and other similar information provided by a party. For avoidance of doubt, Guest Data shall be deemed Confidential Information of Hotelinking. Each party agrees that it will not disclose, use, modify, copy, reproduce or otherwise divulge such Confidential Information to any third party without the prior written approval of the disclosing party except that the receiving party shall have the right to disclose such Confidential Information to the extent required by applicable law or to the directors, officers or employees of the receiving party who have a need to know such Confidential Information in order to perform its obligations under the Agreement and to the extent such directors, officers or employees are subject to obligations of confidentiality and non-disclosure that are substantially similar to the obligations set forth in the Agreement. The prohibitions contained in this Section will not apply to information (i) already lawfully known to the receiving party prior to such disclosure by the disclosing party; (ii) independently developed by the receiving party without access to or use of the disclosing party’s Confidential Information; (iii) disclosed in published materials; (iv) generally known to the public; or (v) lawfully obtained from any third party. In addition, a party will not be considered to have breached its obligations under the Agreement to the extent Confidential Information is required to be disclosed by any governmental authority, provided that, to the extent legally practicable, the receiving party advises the disclosing party prior to making such disclosure in order that the disclosing party may object to such disclosure, take action to ensure confidential treatment of the Confidential Information, or take such other action as it considers appropriate to protect the Confidential Information.</p>
			<h3>Dispute Resolution; Governing Law</h3>
			<p>In the event of a reward dispute or mistake between a Hotel and User, Hotelinking may in its sole discretion unilaterally make adjustments to User reward points. To the extent any disputes arise under the Agreement or otherwise between the parties, the parties will first attempt in good faith to resolve their dispute informally. This Agreement is governed by the State of Illinois and you expressly agree to the exclusive jurisdiction for any claim or dispute with Hotelinking in the federal and state courts within the jurisdiction of the United States District Court for the Northern District of Illinois. The United Nations Convention on Contracts for the International Sale of Goods will not apply to the Agreement.</p>
			<h3>Indemnification</h3>
			<p>You will defend, indemnify, and hold Hotelinking and its affiliates and their respective directors, officers, employees, agents and representatives harmless from and against any third party suit, proceeding, assertion against any damages, judgments, liability, costs and expenses (including without limitation any reasonable attorneys’ fees) incurred arising from your breach of this Agreement, your unauthorized use or misuse of the Hotelinking Programs or any unauthorized combination of any Hotelinking Program with any hardware, software, products, data or other materials not specified or provided by Hotelinking.</p>
			<h3>Limitation of Liability</h3>
			<p>Hotelinking’s aggregate liability for all claims (including claims for indemnification of third party damages) arising out of the Agreement, whether in contract, tort or otherwise, will not exceed the amount of fees paid by you to Hotelinking under the Agreement during the twelve (12) months preceding the date on which the claim occurred. To the maximum extent permitted by applicable law, in no event will Hotelinking be liable for any loss of business profits, business interruption, loss of data or any special, indirect, exemplary, incidental or consequential damages arising from or in relation to the Agreement or the use of the Services, however caused and regardless of theory of liability. In addition, Hotelinking will not be liable for damage (physical or otherwise) incurred by you upon any asset or property from the installation or removal of any Hotelinking product or add-on in-store and will not be responsible for replacement or cost of repair if damages occur. This limitation will apply even if such damages were foreseeable and you have been advised or are aware of the possibility of such damages.</p>
			<h3>Notice</h3>
			<p>Except where explicitly provided otherwise herein, any notice required or permitted hereunder will be delivered to the contact person listed on the Order Information as follows (with notice deemed given as indicated): (i) by personal delivery when delivered personally; (ii) by established overnight courier upon written verification of receipt; (iii) by facsimile transmission when receipt is confirmed orally; (iv) by certified or registered mail, return receipt requested, upon verification of receipt; or (v) by electronic delivery when receipt is confirmed orally.</p>
			<h3>Assignment</h3>
			<p>You may not, without the prior written consent of Hotelinking, assign the Agreement, in whole or in part, either voluntarily or by operation of law, and any attempt to do so will be a material default of the Agreement and will be void. The Agreement will be binding upon and will inure to the benefit of the respective parties hereto, their respective successors in interest, legal representatives, heirs and assigns.</p>
			<h3>No Third Party Beneficiaries</h3>
			<p>The Agreement is solely for the benefit of the parties and their successors and permitted assigns, and does not confer any rights or remedies on any other person or entity.</p>
			<h3>Amendment; Waiver</h3>
			<p>This Agreement may be changed only by written agreement signed by both Hotelinking and you. The failure of either party to exercise or enforce any of its rights under the Agreement will not act as a waiver of subsequent breaches and the waiver of any breach will not act as a waiver of subsequent breaches.</p>
			<h3>Severability</h3>
			<p>If any provision of the Agreement is held by a court or other tribunal of competent jurisdiction to be unenforceable, that provision will be enforced to the maximum extent permissible under applicable law and the other provisions of the Agreement will remain in full force and effect.</p>
			<h3>Force Majeure</h3>
			<p>Neither party shall be liable to the other if such party is prevented from performing any of its obligations under the Agreement (excluding fee payment obligations) due to any cause beyond the party’s reasonable control including, without limitation, an act of God, fire, flood, explosion, terrorism, war, embargo, government regulation, civil or military authority, acts or omissions of carriers, transmitters, providers, or acts of vandals, or hackers. The time for that party’s performance will be extended for the period of the delay or failure to perform due to such occurrence, except that you will not be excused from the payment of any sums of money owed by you to Hotelinking provided prior to the force majeure event.</p>
			<h3>Independent Contractor</h3>
			<p>The Agreement will not be construed as creating or constituting a partnership, joint venture, or agency relationship between the parties. Neither party will have the power to bind the other or incur obligations on the other’s behalf without the other’s prior written consent.</p>
			<h3>Compliance with Laws</h3>
			<p>Each party will comply with all applicable laws, regulations, and ordinances relating to their performance hereunder.</p>
			<h3>Entire Agreement</h3>
			<p>The Agreement will constitute the entire agreement between Hotelinking and you with respect to the subject matter hereof and all prior oral or written agreements, representations or statements with respect to such subject matter are superseded hereby.</p>
			<h3>User Disputes</h3>
			<p>You agree that you are solely responsible for your interactions with any other user, Rewards Provider or third party in connection with the Service (or any third party service with which the Service is integrated), and FiveStars will have no liability or responsibility with respect thereto. FiveStars reserves the right, but has no obligation, to become involved in any way with disputes between you and any Rewards Provider or other third party in connection with the Service (or any third party service with which the Service is integrated). In addition, without limiting the foregoing, FiveStars will have no liability or responsibility for any acts or omissions of Rewards Providers with respect to their use of any of your information or your interactions with them.</p>
			<h3>General Rules</h3>
			<p>You shall, as a condition to making any use of the Campaign Platform, be required to follow these rules:</p>
			<ol>
				<li>You won’t send Spam! While you are responsible for making yourself of aware of current anti-SPAM and similar regulations that may be in effect from time to time, as a general rule, you should assume that if you send people mass email without their permission, you’re spamming.</li>
				<li>You won’t violate Hotelinking’s Acceptable Use guidelines, established below, as it may be in effect from time to time, which is part of this Agreement. If you violate any of these rules, Hotelinking, in addition to any other remedies that Hotelinking may have hereunder or otherwise, may suspend or terminate your account.</li>
			</ol>
			<h3>Compliance with Laws</h3>
			<p>You represent and warrant that your use of the Campaign Platform will comply with all applicable laws and regulations. You’re responsible for determining whether Hotelinking’s services are suitable for you to use in light of any regulations such HIPAA, GLB, EU Data Privacy Laws and/or other laws. If you are subject to regulations (such as HIPAA) and you use the Campaign Platform or any other Hotelinking service, then Hotelinking will not be liable if any such service does not meet those requirements.</p>

			<h3>Acceptable Use</h3>
			<p>You shall refrain from using the Campaign Platform to send anything offensive, to promote anything illegal, or to harass anyone. Not in limitation of the foregoing, you may not send:</p>
			<ol>
				<li>Pornography or other sexually explicit Emails</li>
				<li>Emails offering to sell illegal goods or services</li>
				<li>Emails that violate CAN-SPAM Laws or any other applicable laws or regulations</li>
			</ol>
			<h3>Acceptable Use - Prohibited Actions</h3>
			<p>Hotelinking works hard to keep its system clean, but Hotelinking also counts on its guests to pitch in. As such, you may not:</p>
			<ol>
				<li>Send Spam (as noted above).</li>
				<li>Share your password.</li>
				<li>Use any of the Campaign Platform to create a competing product.</li>
				<li>Import or incorporate any of this information into any lists, emails or uploads to our servers: Social Security numbers, passwords, security credentials, or sensitive personal information of any kind.</li>
				<li>Send any messages through the Campaign Platform that are not appropriate for its intended use.</li>
				<li>Use an outside unsubscribe process.</li>
			</ol>

		</div>
	</div>
